name: apiverve_anagramdetector
description: Anagram Detector is a tool for checking if two words or phrases are anagrams of each other. It provides character frequency analysis and similarity scoring.
version: 1.1.13
homepage: https://apiverve.com/marketplace/anagramdetector?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/anagramdetector-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
