// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.AnagramDetector
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("premium")]
        public Premium Premium { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("text1")]
        public string Text1 { get; set; }

        [JsonProperty("text2")]
        public string Text2 { get; set; }

        [JsonProperty("is_anagram")]
        public bool? IsAnagram { get; set; }

        [JsonProperty("cleaned_text1")]
        public string CleanedText1 { get; set; }

        [JsonProperty("cleaned_text2")]
        public string CleanedText2 { get; set; }

        [JsonProperty("sorted_text1")]
        public string SortedText1 { get; set; }

        [JsonProperty("sorted_text2")]
        public string SortedText2 { get; set; }

        [JsonProperty("length_text1")]
        public long? LengthText1 { get; set; }

        [JsonProperty("length_text2")]
        public long? LengthText2 { get; set; }

        [JsonProperty("similarity_percentage")]
        public long? SimilarityPercentage { get; set; }
    }

    public partial class Premium
    {
        [JsonProperty("message")]
        public string Message { get; set; }

        [JsonProperty("upgrade_url")]
        public Uri UpgradeUrl { get; set; }

        [JsonProperty("locked_fields")]
        public string[] LockedFields { get; set; }
    }
}
