// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.AnagramDetector
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("text1")]
        public string Text1 { get; set; }

        [JsonProperty("text2")]
        public string Text2 { get; set; }

        [JsonProperty("is_anagram")]
        public bool IsAnagram { get; set; }

        [JsonProperty("cleaned_text1")]
        public string CleanedText1 { get; set; }

        [JsonProperty("cleaned_text2")]
        public string CleanedText2 { get; set; }

        [JsonProperty("sorted_text1")]
        public string SortedText1 { get; set; }

        [JsonProperty("sorted_text2")]
        public string SortedText2 { get; set; }

        [JsonProperty("length_text1")]
        public long LengthText1 { get; set; }

        [JsonProperty("length_text2")]
        public long LengthText2 { get; set; }

        [JsonProperty("character_frequency_text1")]
        public CharacterFrequencyText1 CharacterFrequencyText1 { get; set; }

        [JsonProperty("character_frequency_text2")]
        public CharacterFrequencyText1 CharacterFrequencyText2 { get; set; }

        [JsonProperty("common_characters")]
        public CharacterFrequencyText1 CommonCharacters { get; set; }

        [JsonProperty("unique_to_text1")]
        public UniqueToText UniqueToText1 { get; set; }

        [JsonProperty("unique_to_text2")]
        public UniqueToText UniqueToText2 { get; set; }

        [JsonProperty("similarity_percentage")]
        public long SimilarityPercentage { get; set; }

        [JsonProperty("options")]
        public Options Options { get; set; }
    }

    public partial class CharacterFrequencyText1
    {
        [JsonProperty("l")]
        public long L { get; set; }

        [JsonProperty("i")]
        public long I { get; set; }

        [JsonProperty("s")]
        public long S { get; set; }

        [JsonProperty("t")]
        public long T { get; set; }

        [JsonProperty("e")]
        public long E { get; set; }

        [JsonProperty("n")]
        public long N { get; set; }
    }

    public partial class Options
    {
        [JsonProperty("ignore_case")]
        public bool IgnoreCase { get; set; }

        [JsonProperty("ignore_spaces")]
        public bool IgnoreSpaces { get; set; }
    }

    public partial class UniqueToText
    {
    }
}
